import ej1 from "./ejercicios/ej1.js";
import ej1Prompt from "./ejercicios/ej1-prompt.js";
import ej2 from "./ejercicios/ej2.js";
import ej3 from "./ejercicios/ej3.js";
import ej4 from "./ejercicios/ej4.js";
import ej5 from "./ejercicios/ej5.js";
import ej6 from "./ejercicios/ej6.js";
import ej6Prompt from "./ejercicios/ej6-prompt.js";
import ej7 from "./ejercicios/ej7.js";
import ej8 from "./ejercicios/ej8.js";
import ej9 from "./ejercicios/ej9.js";
import ej10 from "./ejercicios/ej10.js";
import ej12 from "./ejercicios/ej12.js";
import ej13 from "./ejercicios/ej13.js";
import ej14 from "./ejercicios/ej14.js";

ej1();
ej1Prompt();
ej2();
ej3();
ej4();
ej5();
ej6();
ej6Prompt();
ej7();
ej8();
ej9();
ej10();
ej12();
ej13();
ej14();